### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [waterloo-rocketry/flight_instr#1]
In the file "flight_instr/software/gyro.cpp", in the function "gyro_test_chipID()", the line "`while (!Wire.available());`" may be removed.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by amihaila** [comment]
Archiving repository, won't fix.
